import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "⚙ setting",
  description: "Generated by create next app",
};

export default function SettingLayout(
  props: Readonly<{
    children: React.ReactNode;
    paralleA: React.ReactNode;
    paralleB: React.ReactNode;
  }>
) {
  const { children, paralleA, paralleB } = props;
  return (
    <>
      <div id="root">
        {paralleA}
        <div className="setting-container">{children}</div>
        {paralleB}
      </div>
    </>
  );
}
