import type { Metadata } from "next";

/**
 * use Metadata API to modify the <head> HTML elements
 * such as title description meta and so on
 *
 * It can be export in layout.js or page.js
 */
export const metadata: Metadata = {
  title: "Route Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <p>shared layout</p>
      <p>不同的 URL， 相同 layout 布局</p>
      {children}
    </div>
  );
}
